# Generated by Django 5.0.14 on 2026-02-13 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epos_qbo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runjob',
            name='continue_on_failure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runjob',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runjob',
            name='parallel',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='runjob',
            name='queued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='runjob',
            name='stagger_seconds',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
