# Generated by Django 5.0.14 on 2026-02-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epos_qbo", "0002_runjob_continue_on_failure_runjob_dispatched_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="runartifact",
            name="reconcile_epos_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="runartifact",
            name="reconcile_epos_total",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="runartifact",
            name="reconcile_qbo_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="runartifact",
            name="reconcile_qbo_total",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
