# Generated by Django 5.0.14 on 2026-02-16 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epos_qbo', '0003_runartifact_reconcile_totals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='runartifact',
            name='reconcile_difference',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='runartifact',
            name='reconcile_epos_total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='runartifact',
            name='reconcile_qbo_total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddIndex(
            model_name='runartifact',
            index=models.Index(fields=['company_key', '-processed_at'], name='epos_qbo_ru_company_40b0df_idx'),
        ),
        migrations.AddIndex(
            model_name='runartifact',
            index=models.Index(fields=['company_key', 'target_date'], name='epos_qbo_ru_company_e591a3_idx'),
        ),
        migrations.AddIndex(
            model_name='runartifact',
            index=models.Index(fields=['company_key', 'reconcile_status'], name='epos_qbo_ru_company_865600_idx'),
        ),
        migrations.AddIndex(
            model_name='runjob',
            index=models.Index(fields=['status', '-created_at'], name='epos_qbo_ru_status_0ba7da_idx'),
        ),
        migrations.AddIndex(
            model_name='runjob',
            index=models.Index(fields=['company_key', '-created_at'], name='epos_qbo_ru_company_c7b636_idx'),
        ),
    ]
