# Generated by Django 5.0.14 on 2026-02-20 00:00

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("epos_qbo", "0004_decimal_and_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RunSchedule",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[("single_company", "Single Company"), ("all_companies", "All Companies")],
                        default="all_companies",
                        max_length=32,
                    ),
                ),
                ("company_key", models.SlugField(blank=True, max_length=64, null=True)),
                ("cron_expr", models.CharField(max_length=120)),
                ("timezone_name", models.CharField(default="UTC", max_length=64)),
                (
                    "target_date_mode",
                    models.CharField(
                        choices=[("trading_date", "Target Trading Date")],
                        default="trading_date",
                        max_length=32,
                    ),
                ),
                ("parallel", models.PositiveSmallIntegerField(default=2)),
                ("stagger_seconds", models.PositiveSmallIntegerField(default=2)),
                ("continue_on_failure", models.BooleanField(default=False)),
                ("next_fire_at", models.DateTimeField(blank=True, null=True)),
                ("last_fired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("queued", "Queued"),
                            ("skipped_overlap", "Skipped (Overlap)"),
                            ("skipped_invalid", "Skipped (Invalid)"),
                            ("error", "Error"),
                        ],
                        max_length=32,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("is_system_managed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_run_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_run_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "created_at"],
                "permissions": [("can_manage_schedules", "Can manage run schedules")],
            },
        ),
        migrations.AddIndex(
            model_name="runschedule",
            index=models.Index(fields=["enabled", "next_fire_at"], name="epos_qbo_rs_enabled_next_idx"),
        ),
        migrations.AddIndex(
            model_name="runschedule",
            index=models.Index(fields=["is_system_managed", "enabled"], name="epos_qbo_rs_system_enabled_idx"),
        ),
        migrations.AddIndex(
            model_name="runschedule",
            index=models.Index(fields=["scope", "company_key"], name="epos_qbo_rs_scope_company_idx"),
        ),
        migrations.AddField(
            model_name="runjob",
            name="scheduled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_jobs",
                to="epos_qbo.runschedule",
            ),
        ),
        migrations.AddIndex(
            model_name="runjob",
            index=models.Index(fields=["scheduled_by", "status", "-created_at"], name="epos_qbo_rj_sched_status_idx"),
        ),
        migrations.CreateModel(
            name="RunScheduleEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("skipped_overlap", "Skipped Overlap"),
                            ("skipped_invalid", "Skipped Invalid"),
                            ("error", "Error"),
                            ("fallback_enabled", "Fallback Enabled"),
                            ("fallback_disabled", "Fallback Disabled"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("payload_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_events",
                        to="epos_qbo.runjob",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="epos_qbo.runschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="runscheduleevent",
            index=models.Index(fields=["event_type", "-created_at"], name="epos_qbo_rse_type_created_idx"),
        ),
        migrations.AddIndex(
            model_name="runscheduleevent",
            index=models.Index(fields=["schedule", "-created_at"], name="epos_qbo_rse_sched_created_idx"),
        ),
    ]
