# Generated by Django 5.0.14 on 2026-02-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epos_qbo", "0005_run_schedule_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runscheduleevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("skipped_overlap", "Skipped Overlap"),
                    ("skipped_invalid", "Skipped Invalid"),
                    ("error", "Error"),
                    ("fallback_enabled", "Fallback Enabled"),
                    ("fallback_disabled", "Fallback Disabled"),
                    ("run_succeeded", "Run Succeeded"),
                    ("run_failed", "Run Failed"),
                ],
                max_length=32,
            ),
        ),
    ]
