# Generated by Django 5.0.14 on 2026-02-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epos_qbo', '0006_alter_runscheduleevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerWorkerHeartbeat',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last_seen', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Scheduler worker heartbeat',
                'verbose_name_plural': 'Scheduler worker heartbeats',
            },
        ),
    ]
