# Generated by Django 5.0.14 on 2026-02-21 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_portal_settings_singleton(apps, schema_editor):
    PortalSettings = apps.get_model("epos_qbo", "PortalSettings")
    PortalSettings.objects.get_or_create(id=1, defaults={})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('epos_qbo', '0007_scheduler_worker_heartbeat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardUserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_overview_company_key', models.CharField(blank=True, max_length=64, null=True)),
                ('default_revenue_period', models.CharField(default='7d', max_length=16)),
                ('notify_on_run_failure', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard user preference',
                'verbose_name_plural': 'Dashboard user preferences',
            },
        ),
        migrations.CreateModel(
            name='PortalSettings',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('default_parallel', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('default_stagger_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stale_hours_warning', models.PositiveIntegerField(blank=True, null=True)),
                ('refresh_expiring_days', models.PositiveIntegerField(blank=True, null=True)),
                ('reconcile_diff_warning', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reauth_guidance', models.TextField(blank=True, null=True)),
                ('dashboard_timezone', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_portal_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portal settings',
                'verbose_name_plural': 'Portal settings',
            },
        ),
        migrations.RunPython(create_portal_settings_singleton, noop),
    ]
