# Generated by Django 5.0.14 on 2026-02-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("epos_qbo", "0008_portal_settings_and_user_preferences"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portalsettings",
            options={
                "permissions": [
                    ("can_manage_portal_settings", "Can manage portal settings"),
                ],
                "verbose_name": "Portal settings",
                "verbose_name_plural": "Portal settings",
            },
        ),
    ]
