# Generated by Django 5.0.14 on 2026-04-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epos_qbo', '0009_portalsettings_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='runartifact',
            name='kind',
            field=models.CharField(choices=[('sales_upload', 'Sales Upload'), ('inventory_audit', 'Inventory Audit')], default='sales_upload', max_length=32),
        ),
        migrations.AddField(
            model_name='runjob',
            name='inventory_options_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='runjob',
            name='scope',
            field=models.CharField(choices=[('single_company', 'Single Company'), ('all_companies', 'All Companies'), ('inventory_sync', 'Inventory Sync')], max_length=32),
        ),
        migrations.AlterField(
            model_name='runschedule',
            name='scope',
            field=models.CharField(choices=[('single_company', 'Single Company'), ('all_companies', 'All Companies'), ('inventory_sync', 'Inventory Sync')], default='all_companies', max_length=32),
        ),
    ]
