# Generated by Django 5.0.14 on 2026-04-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epos_qbo', '0014_correct_weekly_inventory_default_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='runschedule',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runschedule',
            name='run_once_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runschedule',
            name='schedule_type',
            field=models.CharField(choices=[('recurring', 'Recurring'), ('one_time', 'One-time')], default='recurring', max_length=16),
        ),
        migrations.AlterField(
            model_name='runschedule',
            name='cron_expr',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='runscheduleevent',
            name='event_type',
            field=models.CharField(choices=[('queued', 'Queued'), ('skipped_overlap', 'Skipped Overlap'), ('skipped_invalid', 'Skipped Invalid'), ('error', 'Error'), ('one_time_completed', 'One-time Completed'), ('fallback_enabled', 'Fallback Enabled'), ('fallback_disabled', 'Fallback Disabled'), ('run_succeeded', 'Run Succeeded'), ('run_failed', 'Run Failed')], max_length=32),
        ),
    ]
