# Generated by Django 5.0.14 on 2026-05-01 03:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epos_qbo', '0015_runschedule_completed_at_runschedule_run_once_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_key', models.SlugField(max_length=64)),
                ('product_name', models.CharField(max_length=255)),
                ('normalized_product_name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('status_code', models.CharField(blank=True, max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('reason_group', models.CharField(blank=True, db_index=True, max_length=64)),
                ('epos_expected_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('qbo_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('delta', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('source_row_json', models.JSONField(blank=True, default=dict)),
                ('suggested_next_step', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('ignored', 'Ignored'), ('manually_resolved', 'Manually resolved'), ('resolved_by_rerun', 'Resolved by rerun')], db_index=True, default='open', max_length=32)),
                ('resolution_type', models.CharField(blank=True, max_length=64)),
                ('operator_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen_run_label', models.CharField(blank=True, max_length=64)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_review_items', to='epos_qbo.runartifact')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_inventory_review_items', to=settings.AUTH_USER_MODEL)),
                ('run_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_review_items', to='epos_qbo.runjob')),
            ],
            options={
                'ordering': ['-last_seen_at', '-occurrence_count', 'product_name'],
                'indexes': [models.Index(fields=['company_key', 'is_active', 'review_status'], name='inv_review_company_active_idx'), models.Index(fields=['company_key', 'reason_group', 'is_active'], name='inv_review_company_reason_idx'), models.Index(fields=['company_key', 'normalized_product_name'], name='inv_review_company_norm_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='inventoryreviewitem',
            constraint=models.UniqueConstraint(fields=('company_key', 'normalized_product_name', 'reason_group', 'status_code'), name='uniq_inventory_review_item_key'),
        ),
    ]
