# Generated by Django 5.0.14 on 2026-05-09 04:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epos_qbo', '0015_runschedule_completed_at_runschedule_run_once_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReviewAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_key', models.SlugField(max_length=64)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_review_acknowledgement', to='epos_qbo.runartifact')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_review_acknowledgements', to=settings.AUTH_USER_MODEL)),
                ('run_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_review_acknowledgements', to='epos_qbo.runjob')),
            ],
            options={
                'ordering': ['-reviewed_at'],
                'indexes': [models.Index(fields=['company_key', '-reviewed_at'], name='epos_qbo_inv_ack_company_idx')],
            },
        ),
    ]
